org.gradle.jvmargs=-Xmx4000M
org.gradle.daemon=false
org.gradle.configuration-cache=true

shadowjar_version=9.4.1

# NeoForge: https://projects.neoforged.net/neoforged/neoforge
base_minecraft_version=26.1
minecraft_version=26.1.2
neoforge_version=26.1.2.61-beta
mdg_version=2.0.141

beanification_version=1.9.120
pkginfoutil_version=1.0.1

jei_version=19.8.2.99

mod_id=voidfog
mod_major_version=2.2
mod_version=0
