modLoader="javafml"
loaderVersion="[41,)"
issueTrackerURL="https://github.com/Tamaized/Void-Fog/issues"
license="All Rights Reserved"
[[mods]]
modId="voidfog"
version="${version}"
displayName="VoidFog"
credits=""
authors="Tamaized"
description='''

'''

[[dependencies.voidscape]]
    modId="forge"
    mandatory=true
    versionRange="[39.0.0,)"
    ordering="NONE"
    side="BOTH"