modLoader="javafml"
loaderVersion="[46,)"
issueTrackerURL="https://github.com/Tamaized/Void-Fog/issues"
license="All Rights Reserved"
[[mods]]
modId="voidfog"
version="${version}"
displayName="VoidFog"
credits=""
authors="Tamaized"
description='''
displayTest="IGNORE_ALL_VERSION"

'''

[[dependencies.voidfog]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"