modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/Tamaized/Void-Fog/issues"
license="All Rights Reserved"

[[mods]]
    modId="voidfog"
    version="${file.jarVersion}"
    displayName="VoidFog"
    credits=""
    authors="Tamaized"
    displayTest="IGNORE_ALL_VERSION"
    description='''

    '''

[[dependencies.voidfog]]
    modId="neoforge"
    type="required"
    versionRange="[21,)"
    ordering="NONE"
    side="BOTH"