@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
@TypeUseAreNonnullByDefault
package tamaized.voidfog;

import com.mojang.logging.annotations.MethodsReturnNonnullByDefault;
import tamaized.pkginfoutil.TypeUseAreNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;